
const Images = {
    Logo: require('./Logo/Logo.png'),
    HLogo: require('./Logo/HLogo.png'),
    LF: require('./Icon/arrow_left.png'),
    search: require('./Icon/search.png'),
    like: require('./Icon/Like.png'),
    Dlike: require('./Icon/DLike.png'),
    DDown: require('./Icon/drop-down.png'),
    filter: require('./Icon/filter.png'),
    NF: require('./Icon/notification.png'),
    home: require('./Icon/home.png'),
    order: require('./Icon/order.png'),
    profile: require('./Icon/profile.png'),
    basket: require('./Icon/basket.png'),
    category: require('./Icon/category.png'),
    HWatchList: require('./Icon/HWachList.png'),
    delete: require('./Icon/delete.png'),
    Add: require('./Icon/addition.png'),
    Sub: require('./Icon/remove.png'),
    location: require('./Icon/location.png'),
    pen: require('./Icon/pencile.png'),
    Shipping: require('./Icon/Shipping.png'),
    right: require('./Icon/right.png'),
    OnlinePayment: require('./Icon/OPayment.png'),
    OflinePayment: require('./Icon/OflinePayment.png'),
    ThreeDots: require('./Icon/ThreeDots.png'),
    Share: require('./Icon/Share.png'),
    download: require('./Icon/download.png'),
    Print: require('./Icon/print.png'),
    review: require('./Icon/review.png'),
    BuyNow: require('./Icon/BuyNow.png'),
    BuyNow2: require('./Icon/BuyNow2.png'),
    AddCart: require('./Icon/AddCart.png'),
    AddToCart: require('./Icon/AddToCart.png'),
    ShareDot: require('./Icon/ShareDot.png'),
    Camera: require('./Icon/Camera.png'),
    PUser: require('./Icon/PUser.png'),
    Pstar: require('./Icon/PStar.png'),
    PAddress: require('./Icon/Paddress.png'),
    PLock: require('./Icon/PLock.png'),
    PHelp: require('./Icon/PHelp.png'),
    PLogout: require('./Icon/PLogOut.png'),
    PCart: require('./Icon/PCart.png'),
    PNotification: require('./Icon/PNotification.png'),
    PEmail: require('./Icon/PEmail.png'),
    PCalender: require('./Icon/PCalender.png'),
    forward: require('./Icon/forward.png'),
    star: require('./Icon/star.png'),
    WhiteStar: require('./Icon/WhiteStar.png'),
    Ostar: require('./Icon/Ostar.png'),
    OstarF: require('./Icon/OstarF.png'),



    PC: require('./other/PC.png'),
    SF: require('./other/SF.png'),
    SNP: require('./other/SN-P.png'),
    SVOTP: require('./other/SV-OTP.png'),
    FPOTP: require('./other/FP-OTP.png'),
    SPC: require('./other/S-PC.png'),
    FP: require('./other/F-P.png'),
    LoginFirst: require('./other/LF.png'),
    razorpay: require('./other/razorpay.png'),
    instamojo: require('./other/instamojo.png'),
    PayU: require('./other/PayU.png'),
    PayPal: require('./other/PayPal.png'),
    OderSuccesful: require('./other/OderSeccesful.png'),
    User: require('./other/UserPassportSize.png'),
    PendingOrder: require('./other/PendingOrder.png'),
    F1Img: require('./other/FirstScreen.png'),
    F2Img: require('./other/SecondScreen.png'),
    F3Img: require('./other/ThirdScreen.png'),
    F4Img: require('./other/FourScreen.png'),


    HDI1: require('./Discount/HDI.png'),
    HDI: require('./Discount/DctImg.png'),
    HDI25: require('./Discount/DicImg25.png'),
    HDI30: require('./Discount/DisImg30.png'),

    Apple: require('./Fruits/Apple.png'),
    ArabicGinger: require('./Fruits/ArabicGinger.png'),
    Baroccoli: require('./Fruits/Baroccoli.png'),
    BeatRoot: require('./Fruits/BeatRoot.png'),
    Butternut: require('./Fruits/Butternut.png'),
    BellPaperRed: require('./Fruits/BellPaperRed.png'),
    Carrot: require('./Fruits/Carrot.png'),
    Lettuce: require('./Fruits/Lettuce.png'),
    Orange: require('./Fruits/Mosambi.png'),
    Nescafe: require('./Fruits/Nescafe.png'),
    Onion: require('./Fruits/Onion.png'),
    Pineapple: require('./Fruits/Pineapple.png'),
    PuffsChips: require('./Fruits/PuffsChips.png'),


};

export default Images;
